name: Test Coverage

on:
  push:
    branches: [master]
    paths:
      - 'app/**'
  workflow_dispatch:
permissions:
  contents: write

jobs:
  test-report-with-coverage:
    name: Test and report coverage
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install pytest-cov coverage-badge
          pip install -r requirements.txt

      - name: Test with pytest and coverage
        run: |
          pytest --cov=app --cov-report=xml --cov-report=term

      - name: Coverage report
        run: |
          coverage-badge -o ./badges/coverage.svg

      - name: Upload coverage badge
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: badges
          target-folder: docs

    env:
      JWT_ENCODING_KEY: ${{ secrets.JWT_ENCODING_KEY }}
