name: Orders System API docker build and push

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/orders-system-api:latest
        labels: ${{ secrets.DOCKERHUB_USERNAME }}/orders-system-api:latest

    - name: Deploy docker image to Render
      # Only run this step when the branch is master
      if: github.ref == 'refs/heads/master'
      env:
        DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
      run: |
        curl "$DEPLOY_URL"

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
    
